url: www.datamantra.io
baseurl: /datamantra/

# Site settings
title: Data Mantra
email: hello@datamantra.io
description: "Spark and Hadoop specialists"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 8FCB94
  secondary: 42DF4F
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Madhukara Phatak
  pic: 1
  position: Consultant
  social:
    - title: twitter
      url: https://twitter.com/madhukaraphatak
    - title: github
      url:  https://github.com/phatak-dev
    - title: linkedin
      url: https://www.linkedin.com/in/madhukaraphatak

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/datamantra
  - title: github
    url: http://github.com/datamantra


# Build settings
markdown: kramdown
permalink: pretty